configured_endpoints: 38
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/the-frontside-software-inc%2Fjsr-api-8d4e99f1d713efb471528dbe5307bcd6c138d286b0b1ce58aaae1c21602b0eea.yml
